Fix looking up the yarn lock hash

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -40,12 +40,17 @@ runs:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ github.token }}
+
+    - name: Set image tag env
+      shell: bash
+      run: |
+        echo IMAGE_TAG="ghcr.io/${{ inputs.namespace }}/${{ inputs.imageName }}" >> $GITHUB_ENV
       
     - name: Pull base image
       id: pull_base_image
       shell: bash
       run: |
-        docker pull ghcr.io/${{ inputs.namespace }}/${{ inputs.imageName }} || echo "STATUS=failed" >> $GITHUB_OUTPUT
+        docker pull ${{ env.IMAGE_TAG }} || echo "STATUS=failed" >> $GITHUB_OUTPUT
       continue-on-error: true
 
     - name: Get previous yarn lock hash
@@ -53,7 +58,7 @@ runs:
       if: steps.pull_base_image.outputs.STATUS != 'failed'
       shell: bash
       run: |
-        echo PREVIOUS_YARN_LOCK_HASH="$(docker inspect --format='{{index .Config.Labels "yarn-lock-hash"}}' ${{ inputs.imageName }})" >> $GITHUB_ENV
+        echo PREVIOUS_YARN_LOCK_HASH="$(docker inspect --format='{{index .Config.Labels "yarn-lock-hash"}}' ${{ env.IMAGE_TAG }})" >> $GITHUB_ENV
 
     - name: Compare yarn.lock hash with label stored yarn.lock hash
       id: yarn_lock_hash_check
@@ -68,7 +73,7 @@ runs:
       with:
         context: .
         file: ${{inputs.dockerfilePath}}
-        tags: ghcr.io/${{inputs.namespace}}/${{inputs.imageName}}:latest
+        tags: ${{ env.IMAGE_TAG }}:latest
         push: true
         build-args: |
           DD_API_KEY="${{inputs.datadogApiKey}}"
